version: '2'

services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    restart: always